# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rspec', '~> 3.10'
gem 'activerecord'
gem 'standalone_migrations'
gem 'sqlite3', '~> 2.2'
gem 'rubocop'
